// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	inspectTextFile: (path: string) => typedError<TextFileSummary, CommandError>(__TAURI_INVOKE("inspect_text_file", { path })),
};

/* Types */
/**
 *  What the interface receives when a command fails.
 * 
 *  This is the wire format. It is deliberately small: the interface needs to
 *  know *which* failure happened and *what to tell the user*, and nothing else
 *  should cross the boundary.
 */
export type CommandError = {
	/**
	 *  Stable identifier. Chassis codes are bare (`not_found`); program codes
	 *  are namespaced by the program (`demo.not_text`).
	 */
	code: string,
	/**  Plain-language sentence, safe to show a customer. */
	message: string,
};

export type TextFileSummary = {
	name: string,
	sizeBytes: number,
	lines: number,
	words: number,
	characters: number,
	/**  The start of the file, at most `PREVIEW_CHARS` characters. */
	preview: string,
	/**  True when the preview stops before the end of the file. */
	truncated: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

