//! Where `src/chassis/bindings.ts` and `src/app/bindings.ts` come from.
//!
//! Both files are generated from the Rust command signatures by tauri-specta
//! and committed. They are regenerated by `npm run bindings` (a test, so it
//! needs no running app) and on every debug launch. CI regenerates them and
//! fails if the result differs from what is committed, so a Rust signature
//! change without a matching interface change is a build failure rather than
//! a runtime surprise.

use std::path::{Path, PathBuf};

use specta_typescript::Typescript;

fn exporter() -> Typescript {
    // The generated file declares helpers it does not always use, which the
    // interface's `noUnusedLocals` would reject. Its exports are still fully
    // type-checked at every import site, which is where mistakes happen.
    Typescript::default().header("// @ts-nocheck")
}

fn interface_src() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("src")
}

pub fn export() -> Result<(), specta_typescript::Error> {
    let src = interface_src();
    crate::chassis::specta().export(exporter(), src.join("chassis").join("bindings.ts"))?;
    crate::commands::specta().export(exporter(), src.join("app").join("bindings.ts"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    #[test]
    fn export() {
        super::export().expect("failed to export the TypeScript bindings");
    }
}
