// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getDiagnostics: () => typedError<Diagnostics, CommandError>(__TAURI_INVOKE("plugin:chassis|get_diagnostics")),
};

/* Constants */
export const CLOSE_TO_TRAY_KEY = "chassis.closeToTray" as const;

export const MAIN_WINDOW = "main" as const;

export const SETTINGS_STORE_FILE = "settings.json" as const;

/* Types */
/**
 *  What the interface receives when a command fails.
 * 
 *  This is the wire format. It is deliberately small: the interface needs to
 *  know *which* failure happened and *what to tell the user*, and nothing else
 *  should cross the boundary.
 */
export type CommandError = {
	/**
	 *  Stable identifier. Chassis codes are bare (`not_found`); program codes
	 *  are namespaced by the program (`demo.not_text`).
	 */
	code: string,
	/**  Plain-language sentence, safe to show a customer. */
	message: string,
};

export type Diagnostics = {
	appName: string,
	appVersion: string,
	identifier: string,
	tauriVersion: string,
	webviewVersion: string,
	os: string,
	arch: string,
	logFile: string,
	/**  The last lines of the active log file, oldest first. */
	recentLog: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

